apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-pos-tech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-pos-tech
  template:
    metadata:
      labels:
        app: tech-challenge-pos-tech
    spec:
      containers:
        - name: tech-challenge-pos-tech
          image: gleniomontovani/tech-challenge-pos-tech:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
                        