apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-pos-tech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-pos-tech
  template:
    metadata:
      labels:
        app: tech-challenge-pos-tech
    spec:
      containers:
        - name: tech-challenge-pos-tech
          image: gleniomontovani/tech-challenge-pos-tech:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-pos-tech-config
                  key: DATASOURCE_URL    
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-pos-tech-config
                  key: DATASOURCE_USERNAME  
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATASOURCE_PASSWORD
                  name: tech-challenge-pos-tech-secret            
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
                        