apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-pos-tech-config
                  key: DATASOURCE_DB 
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-pos-tech-config
                  key: DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATASOURCE_PASSWORD
                  name: tech-challenge-pos-tech-secret 
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      restartPolicy: Always 

                   