apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-pos-tech-service
spec:
  selector:
    app: tech-challenge-pos-tech
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  type: NodePort