apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-pos-tech-service
  labels:
    app: tech-challenge-pos-tech
spec:
  selector:
    app: tech-challenge-pos-tech
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  loadBalancerSourceRanges: []