name: Build the Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building the application..."
      - name: Set test flag
        run: echo "TEST_REQUIRED=true" >> $GITHUB_ENV
      - name: Run Test Workflow
        if: success()
        #uses: ./.github/workflows/test.yml
        uses: octo-org/example-repo/.github/workflows/test.yml@main
        with:
          config-path: .github/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: env.DEPLOY_REQUIRED == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying the application..."   
