name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt-hotspot'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml

  build:
    needs: tests
    name: Build maven package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt-hotspot'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build package jar
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload .jar
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: /target/tech-challenge-pos-tech.jar
  deploy:
    needs: build
    name: Deploy on AWS Elastic Beanstall
    runs-on: ubuntu-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          wait_for_environment_recovery: 120
          application_name: tech-challenge-pos-tech
          environment_name: Appspringboot-env
          version_label: latest-${{github.sha}}
          region: us-east-1
          deployment_package: tech-challenge-pos-tech.jar

   
