name: Test Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: echo "Testing the application..."
      - name: Set deploy flag
        run: echo "DEPLOY_REQUIRED=true" >> $GITHUB_ENV



